//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace UniToLua
{
    
    
    public class LuaBinder
    {
        
        public static void Bind(UniLua.LuaState L)
        {
			L.BeginModule(null);
			L.BeginModule("TestUniToLua");
			L.BeginModule("TestClasses");
			TestUniToLua_TestClasses_MyStaticLibWrap.Register(L);
			TestUniToLua_TestClasses_MyClassWrap.Register(L);
			TestUniToLua_TestClasses_MyEnumWrap.Register(L);
			L.EndModule();
			L.EndModule();
			L.EndModule();
        }
    }
}
