//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace UniToLua
{
    
    
    public class TestUniToLua_TestClasses_MyEnumWrap
    {
        
        public static void Register(UniLua.ILuaState L)
        {
			L.BeginEnum("MyEnum");
			L.RegVar("A", get_A, null);
			L.RegVar("B", get_B, null);
			L.RegVar("C", get_C, null);
			L.EndEnum();
        }
        
        private static int get_A(UniLua.ILuaState L)
        {
			L.PushLightUserData(TestUniToLua.TestClasses.MyEnum.A);
			return 1;
        }
        
        private static int get_B(UniLua.ILuaState L)
        {
			L.PushLightUserData(TestUniToLua.TestClasses.MyEnum.B);
			return 1;
        }
        
        private static int get_C(UniLua.ILuaState L)
        {
			L.PushLightUserData(TestUniToLua.TestClasses.MyEnum.C);
			return 1;
        }
    }
}
